kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-dep
  namespace: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: nitinpanwar6963/fitness-app
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "250Mi"
        envFrom:
        - configMapRef:
            name: flask-config
