apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-state
  namespace: flask
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
       app: mysql

  template:
    metadata:
      name: mysql-temp
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-secret
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
